default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram_bot_token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
  webhook_token: <%= ENV["WEBHOOK_TOKEN"] %>
  g_config_var: <%= ENV["G_CONFIG_VAR"] %>
  g_config_file: ./config/g_drive_config.json
  # http://spreadsheets.google.com/ccc?key=...
  spreadsheet_key: 15DD8yQCyRyKIg0BFTFQ9i1SKw2Q-lc9GH32hw8PKyw4

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
