default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram_bot_token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
  webhook_token: <%= ENV["WEBHOOK_TOKEN"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
